### ISSUE TITLE
Add support for libcamera.

### ISSUE THREAD

**Issue by mriesch-wv** [pengutronix/umpf#11]
The libcamera project [0](https://libcamera.org/) uses the meson build system and should be easy to address in principle. However, it is all about the details :-)

libcamera uses [semantic versioning](https://semver.org/) and does not allow appending the extraversion in the current form (dot separated, e.g., "0.0.4.20230213-1") . Semantic versioning allows for build metadata, which is separated from the version with a plus sign (the metadata itself can be dot separated,  e.g., "0.0.4+20230213.1"). Note that using a dash "-" in the build metadata is not allowed.

 - Is it envisaged to have project specific extraversion handling in umpf?
 - Is it safe to assume that all meson projects use semantic versioning anyway and switching to "+20230213.1" is a suitable solution?

**Comment by michaelolbrich** [comment]
> *  Is it envisaged to have project specific extraversion handling in umpf?

Yes, if necessary. There is quite a bit project specific stuff there already.

> *  Is it safe to assume that all meson projects use semantic versioning anyway and switching to "+20230213.1" is a suitable solution?

We explicitly changed it to use the dot (instead of the original minus) the handle GStreamer packages. So I'm not sure if we can change it for all packages.

This needs some investigation to see what is acceptable to which package.

**Comment by mriesch-wv** [comment]
> > * Is it envisaged to have project specific extraversion handling in umpf?
> 
> Yes, if necessary. There is quite a bit project specific stuff there already.

Could you point me to examples of project specific stuff?

> > * Is it safe to assume that all meson projects use semantic versioning anyway and switching to "+20230213.1" is a suitable solution?
> 
> We explicitly changed it to use the dot (instead of the original minus) the handle GStreamer packages. So I'm not sure if we can change it for all packages.
> 
> This needs some investigation to see what is acceptable to which package.

I guess package specific is fine, as every project may have its own rules. I think I can tinker around a bit, but any pointers how this should be accomplished will be much appreciated.

**Comment by michaelolbrich** [comment]
For GStreamer we need to do some extra stuff to make it work. It's not not the version directly but the idea is the same: Find something to detect the project and then do the custom stuff:
https://github.com/pengutronix/umpf/blob/cf4f71a4425d4bb40e6272992d2c1b06d33c38f5/umpf#L1062

**Comment by michaelolbrich** [comment]
```
if is_libcamera; then
    version_string="+${version}"
elif ...
    ...
else
    version_string=".${version}"
fi
```
and then use `${version_string}` to patch meson.build. Or something like that.
