### ISSUE TITLE
Only flat tag is annotated.

### ISSUE THREAD

**Issue by mriesch-wv** [pengutronix/umpf#12]
If I checkout a tag and execture `git describe` the tag is not recognized. This works for the flat tag, though, as it is created with the `-F` parameter.

Is it desired behavior that the `mytagname/20230217-1` is a lightweight tag and the `mytagname/20230217-1-flat` is an annotated tag?

**Comment by michaelolbrich** [comment]
It's not in any way deliberate, it just happens to be that way. An annotated tag for `mytagname/20230217-1` does make sense though. I'm not sure what to put in the message. Suggestions?

**Comment by mriesch-wv** [comment]
I'd suggest re-using the message of the commit that bumps the (extra)version. It seems the kernel does the same, there is a commit with the message "Linux 6.2" and a tag with the same message (well, + PGP signature).
