### ISSUE TITLE
The --remote argument is not considered in umpf merge. 

### ISSUE THREAD

**Issue by mriesch-wv** [pengutronix/umpf#14]
I tried to merge a remote branch with `umpf merge --remote=downstream_repo feature/fancy`, but the branch `feature/fancy` was not found. I could resolve this problem by either checking the branch out locally or by using `umpf merge downstream_repo/feature/fancy`. Is the `--remote` argument supposed to work as I expected?

**Comment by michaelolbrich** [comment]
No, the argument is always the full branch name. Exactly what `git merge` would expect as well. The remote argument is mostly there for historic reasons: It can specify the prefix that should removed from the branch when creating the text for the subject and commit message. Now umpf has been improved to detect that automatically so it is no longer needed in most cases.
